apiVersion: v1
kind: Secret
metadata:
  name: common-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  MONGODB_CONNECTION_STRING: {{ .Values.secrets.mongodb | quote }}
  JWT_SECRET: {{ .Values.secrets.jwt | quote }}
  CLOUDINARY_CLOUD_NAME: {{ .Values.secrets.cloudinary.cloudName | quote }}
  CLOUDINARY_API_KEY: {{ .Values.secrets.cloudinary.apiKey | quote }}
  CLOUDINARY_API_SECRET: {{ .Values.secrets.cloudinary.apiSecret | quote }}

